
set(PATTERNS)
if (CMAKE_SHARED_LIBRARY_SUFFIX)
    set(PATTERNS 
      ${PATTERNS}
      "${VTK_INSTALL_DIR}/lib/*${CMAKE_SHARED_LIBRARY_SUFFIX}"
      "${VTK_INSTALL_DIR}/bin/*${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()
if (CMAKE_IMPORT_LIBRARY_SUFFIX)
    set(PATTERNS 
      ${PATTERNS}
      "${VTK_INSTALL_DIR}/lib/*${CMAKE_IMPORT_LIBRARY_SUFFIX}"
      "${VTK_INSTALL_DIR}/bin/*${CMAKE_IMPORT_LIBRARY_SUFFIX}")
endif()

file(GLOB VTK_LIBRARIES
  ${PATTERNS}
)

file(COPY ${VTK_LIBRARIES} DESTINATION ${VTK_RUNTIME_OUTPUT_DIRECTORY})
